apiVersion: v1
kind: ConfigMap
metadata:
  name: platform-config
  namespace: production
data:
  APP_ENV: "production"

  LOG_LEVEL: "info"

  FRONTEND_SERVICE: "frontend-service"

  BACKEND_SERVICE: "backend-service"

  PROMETHEUS_ENABLED: "true"

  LOKI_ENABLED: "true"
