apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
name: backend-rollout

spec:
strategy:
canary:
steps:
- setWeight: 5
- pause:
duration: 300s

```
    - analysis:
        templates:
          - templateName: success-rate-analysis

    - setWeight: 20
    - pause:
        duration: 600s

    - analysis:
        templates:
          - templateName: success-rate-analysis

    - setWeight: 50
    - pause:
        duration: 900s

    - analysis:
        templates:
          - templateName: success-rate-analysis

    - setWeight: 100
```
