apiVersion: v1
kind: Namespace
metadata:
name: production

labels:
pod-security.kubernetes.io/enforce: restricted

```
pod-security.kubernetes.io/audit: restricted

pod-security.kubernetes.io/warn: restricted
```

---

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
name: backend-pdb
namespace: production

spec:
minAvailable: 2

selector:
matchLabels:
app: backend
------------

apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
name: frontend-pdb
namespace: production

spec:
minAvailable: 1

selector:
matchLabels:
app: frontend
