name: Deploy To Kubernetes

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest


    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Install ArgoCD CLI
      run: |
        curl -sSL -o argocd \
        https://github.com/argoproj/argo-cd/releases/latest/download/argocd-linux-amd64

        chmod +x argocd

        sudo mv argocd /usr/local/bin/

    - name: Trigger ArgoCD Sync
      run: |
       argocd app sync frontend-app

        argocd app sync backend-app
